name: Update Documentation

on: [workflow_dispatch]

jobs:
  build:
    name: Create Documentation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET 7.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '7.0.x'

    - name: Cache NuGet Packages
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Dotnet Build
      run: dotnet build -c Documentation

    - name: Pack Documentation
      run: tar -cvf Documentation.tar -C Documentation/_site .

    - name: Save Documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: Documentation.tar

  publish:
    name: Publish Documentation
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages

    - name: Set Git Identity
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@github.com"

    - name: Delete Documenation
      run: |
        rm -rfv ./*
        git rm ** -f

    - name: Load Documentation
      uses: actions/download-artifact@v3
      with:
        name: documentation

    - name: Unpack Documentation
      run: |
        tar -xvf Documentation.tar
        rm Documentation.tar
        git add ** -f

    - name: Commit and Push
      run: |
        git commit -m "Update content of .NET SDK documentation on GitHub Pages web site."
        git push origin gh-pages
