name: Update NuGet Lock Files

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: write

jobs:
  lockfiles:
    name: Update and Commit
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v7

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v6
      with:
        global-json-file: global.json

    - name: Restore Dependencies
      run: dotnet restore --force-evaluate

    - name: Auto-commit changed files
      uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: Update NuGet lock files after Dependabot dependency update.
